<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Part 0: Conceptual Warm Up –  Bowen de Gouw</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<link href="../photos/bdglogo.png" rel="icon" type="image/png">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title"><img src="photos/bdglogo.png" style="height:22px; margin-right:8px;"> Bowen de Gouw</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../professionalsummary.html"> 
<span class="menu-text">Professional Summary</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-academics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Academics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-academics">    
        <li>
    <a class="dropdown-item" href="../classes.html">
 <span class="dropdown-text">Academic Coursework</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../marketing_analytics.html">
 <span class="dropdown-text">Marketing Analytics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../financial_analytics.html">
 <span class="dropdown-text">Financial Analytics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cloud_analytics.html">
 <span class="dropdown-text">Cloud Analytics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../gallery.html"> 
<span class="menu-text">Photo Gallery</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../side_projects.html"> 
<span class="menu-text">Side Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../contact.html"> 
<span class="menu-text">Contact Me</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#part-1-create-your-own-little-market" id="toc-part-1-create-your-own-little-market" class="nav-link active" data-scroll-target="#part-1-create-your-own-little-market">Part 1: Create Your Own Little Market</a></li>
  <li><a href="#part-2-invent-a-simple-trading-rule" id="toc-part-2-invent-a-simple-trading-rule" class="nav-link" data-scroll-target="#part-2-invent-a-simple-trading-rule">Part 2: Invent a Simple Trading Rule</a></li>
  <li><a href="#part-3-turn-actions-into-money" id="toc-part-3-turn-actions-into-money" class="nav-link" data-scroll-target="#part-3-turn-actions-into-money">Part 3: Turn Actions Into Money</a></li>
  <li><a href="#part-4-add-leverage" id="toc-part-4-add-leverage" class="nav-link" data-scroll-target="#part-4-add-leverage">Part 4: Add Leverage</a></li>
  <li><a href="#part-5-introduce-a-survival-rule" id="toc-part-5-introduce-a-survival-rule" class="nav-link" data-scroll-target="#part-5-introduce-a-survival-rule">Part 5: Introduce a Survival Rule</a></li>
  <li><a href="#part-6-a-tiny-shock" id="toc-part-6-a-tiny-shock" class="nav-link" data-scroll-target="#part-6-a-tiny-shock">Part 6: A Tiny Shock</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Part 0: Conceptual Warm Up</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div id="cell-1" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If a strategy is making money 70% of the time, it may seem automatically safe, but this is not necessarily true. A 70% win rate suggests that there is a 30% probability that it is not making money. It may seem logical to choose the strategy because 70% represents a clear majority. However, in a hypothetical example, 70% of the time the strategy may work on a very low-risk basis consistently, where it returns 5% frequently, but when it does not work it may cause a drastic loss, of say -20%. This way of evaluating strategy success is not viable as it does not tell the whole story of risk and analysing the potential upsides and downsides depending on if you are successful or not. Determining whether a strategy is safe depends not only on the frequency of wins, but also on the magnitude of losses, the overall distribution of returns, and the ability to recover from significant losses.</p>
<section id="part-1-create-your-own-little-market" class="level1">
<h1>Part 1: Create Your Own Little Market</h1>
<p>Below is the hypothetical code I would have run if I had not had an issue with the seed value…</p>
<div id="cell-6" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PERSONAL_SEED = 23 # Personal Seed Reflects My Age</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># np.random.seed(PERSONAL_SEED)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-7" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 60-day price series starting at 50</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># start_price = 50</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># days = 60</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># noise_volatility = 0.5</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># daily_noise = np.random.normal(0, noise_volatility, days)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-8" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># daily_noise[0] = 0</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># prices = start_price + np.cumsum(daily_noise)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Reminder about my email - I had an issue with the seed value so am loading in the data here to make it reproducable for the sake off my write-ups that were completed prior to realizing… Thank you for being understanding!</p>
<p>Here is where I loaded in my data that I had written about prior to realising my mistake with the seed values…</p>
<div id="cell-10" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> io</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> <span class="st">"""Day      Price</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="st">        0     1  50.000000</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="st">        1     2  49.593192</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="st">        2     3  49.945004</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="st">        3     4  49.810933</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="st">        4     5  49.569653</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="st">        5     6  50.191958</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="st">        6     7  50.530388</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="st">        7     8  52.124140</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="st">        8     9  51.583857</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="st">        9    10  51.588972</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="st">        10   11  51.807887</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="st">        11   12  52.471780</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="st">        12   13  52.346208</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="st">        13   14  53.142763</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="st">        14   15  53.228172</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="st">        15   16  52.873545</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="st">        16   17  52.807033</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="st">        17   18  52.798354</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="st">        18   19  52.747808</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="st">        19   20  52.465788</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="st">        20   21  52.376270</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="st">        21   22  52.881800</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="st">        22   23  53.342298</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="st">        23   24  54.308843</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="st">        24   25  53.911161</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="st">        25   26  53.405393</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="st">        26   27  54.480783</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a><span class="st">        27   28  54.693353</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="st">        28   29  54.913929</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="st">        29   30  54.505209</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="st">        30   31  54.724156</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a><span class="st">        31   32  54.774017</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a><span class="st">        32   33  54.806720</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="st">        33   34  55.418936</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a><span class="st">        34   35  55.034136</span></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a><span class="st">        35   36  55.130196</span></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a><span class="st">        36   37  54.268569</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a><span class="st">        37   38  54.499199</span></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a><span class="st">        38   39  53.956516</span></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a><span class="st">        39   40  54.868205</span></span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a><span class="st">        40   41  54.201773</span></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a><span class="st">        41   42  55.020469</span></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a><span class="st">        42   43  54.608999</span></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a><span class="st">        43   44  53.809945</span></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a><span class="st">        44   45  53.923201</span></span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a><span class="st">        45   46  54.040150</span></span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a><span class="st">        46   47  53.566538</span></span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a><span class="st">        47   48  52.935750</span></span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a><span class="st">        48   49  51.740817</span></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a><span class="st">        49   50  51.574180</span></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a><span class="st">        50   51  51.745939</span></span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a><span class="st">        51   52  50.732008</span></span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a><span class="st">        52   53  50.797717</span></span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a><span class="st">        53   54  51.599334</span></span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a><span class="st">        54   55  50.717177</span></span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a><span class="st">        55   56  51.000429</span></span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a><span class="st">        56   57  51.274823</span></span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a><span class="st">        57   58  50.967255</span></span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a><span class="st">        58   59  51.129028</span></span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a><span class="st">        59   60  50.577431"""</span></span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(io.StringIO(data), sep<span class="op">=</span><span class="vs">r'\s\s+'</span>, engine<span class="op">=</span><span class="st">'python'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-11" class="cell" data-outputid="c0721544-912c-4507-e555-ac336e2bf1dd" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display first 10 rows</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df.head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">

  <div id="df-a26b7e7d-d1cd-4606-8f1d-38aa3374b665" class="colab-df-container">
    <div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Day</th>
<th data-quarto-table-cell-role="th">Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>50.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>49.593192</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>49.945004</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>49.810933</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>49.569653</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>6</td>
<td>50.191958</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>7</td>
<td>50.530388</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>8</td>
<td>52.124140</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>9</td>
<td>51.583857</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>10</td>
<td>51.588972</td>
</tr>
</tbody>
</table>

</div>
    <div class="colab-df-buttons">

  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-a26b7e7d-d1cd-4606-8f1d-38aa3374b665')" title="Convert this dataframe to an interactive table." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"></path>
  </svg>
    </button>

  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-a26b7e7d-d1cd-4606-8f1d-38aa3374b665 button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-a26b7e7d-d1cd-4606-8f1d-38aa3374b665');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>


    </div>
  </div>
</div>
</div>
<div id="cell-12" class="cell" data-outputid="154c14e2-ddfa-417e-9e36-46990f1ac92b" data-execution_count="7">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot series price</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>plt.plot(df[<span class="st">'Day'</span>], df[<span class="st">'Price'</span>], marker<span class="op">=</span><span class="st">'.'</span>, linestyle<span class="op">=</span><span class="st">'-'</span>, color<span class="op">=</span><span class="st">'#2ca02c'</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'60-Day Simulated Price Series'</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Day'</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Price ($)'</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AD561_Assignment1_BdeGouw_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>I chose the seed value because it is my age, 23 years old (or would have, if things had gone to plan…)</p>
<p>The price on day 20 of my series is roughly $52.46.</p>
<p>My series trends both up and down throughout the 60 day period. As set, the price begins at $50, and begins to trend upwards for the first 35 days, peaking at a price of roughly $55.50. From this point onwards, we then see the price begin to decrease over the remaining 25 days, where the price eventually ends the 60 day period at $50.60. These descriptions of the price change over the 60 day period demonstrates the general trends, however, it is important to know that on a day-to-day basis, there are fluctuations of small increases and decreases that occur. This tells us that although there are general trends occuring over this specific time window, there are still differences on a micro level that are important to consider when analyzing price changes.</p>
<p>If I had to guess tomorrow’s price, I would guess that it is going to be $51. This is because the price over the days prior have fluctuated around that price, and I am expecting that the overall price is going to head on a general trend of increasing as it did that last time it was in the $50-51 price range. However, it is important to understand that this is purely a guess, and to make any further estimations of tomorrow’s price there are better ways of forecasting this.</p>
<p>My chart feels generally pretty calm. This is because over the range of a 60 day period, we see the price fluctuate within a $5.50 range. While we are missing a large amount of context about this price series, I believe that it has remained within a reasonable range despite the general trends discussed prior, as well as the daily price changes. If I were to see the price changing within this range daily and with less consistent upwards or downard trends, we may say that it is volatile, but the small daily changes that create these trends lead me to believe that on the whole it is pretty calm.</p>
</section>
<section id="part-2-invent-a-simple-trading-rule" class="level1">
<h1>Part 2: Invent a Simple Trading Rule</h1>
<div id="cell-15" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>positions <span class="op">=</span> []</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>actions <span class="op">=</span> []</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>current_position <span class="op">=</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-16" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>current_pos <span class="op">=</span> <span class="dv">0</span>  <span class="co"># start with no position</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>positions <span class="op">=</span> []</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>actions <span class="op">=</span> []</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> price <span class="kw">in</span> df[<span class="st">"Price"</span>]:</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Apply rule</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> price <span class="op">&gt;</span> <span class="dv">52</span>:</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>        desired_pos <span class="op">=</span> <span class="op">-</span><span class="dv">1</span>   <span class="co"># short</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> price <span class="op">&lt;</span> <span class="dv">48</span>:</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>        desired_pos <span class="op">=</span> <span class="dv">1</span>    <span class="co"># long</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>        desired_pos <span class="op">=</span> <span class="dv">0</span>    <span class="co"># hold / flat</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Execute trade only if position changes</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> desired_pos <span class="op">==</span> <span class="dv">1</span> <span class="kw">and</span> current_pos <span class="op">!=</span> <span class="dv">1</span>:</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>        action <span class="op">=</span> <span class="st">"GO LONG"</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>        current_pos <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> desired_pos <span class="op">==</span> <span class="op">-</span><span class="dv">1</span> <span class="kw">and</span> current_pos <span class="op">!=</span> <span class="op">-</span><span class="dv">1</span>:</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>        action <span class="op">=</span> <span class="st">"GO SHORT"</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>        current_pos <span class="op">=</span> <span class="op">-</span><span class="dv">1</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>        action <span class="op">=</span> <span class="st">"HOLD"</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    positions.append(current_pos)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>    actions.append(action)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-17" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Position'</span>] <span class="op">=</span> positions</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Action'</span>] <span class="op">=</span> actions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-18" class="cell" data-outputid="ed131040-2f80-4949-d435-cdf55f04998e" data-execution_count="11">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">--- Part 2: Full Trading Table ---"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.to_string())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--- Part 2: Full Trading Table ---
    Day      Price  Position    Action
0     1  50.000000         0      HOLD
1     2  49.593192         0      HOLD
2     3  49.945004         0      HOLD
3     4  49.810933         0      HOLD
4     5  49.569653         0      HOLD
5     6  50.191958         0      HOLD
6     7  50.530388         0      HOLD
7     8  52.124140        -1  GO SHORT
8     9  51.583857        -1      HOLD
9    10  51.588972        -1      HOLD
10   11  51.807887        -1      HOLD
11   12  52.471780        -1      HOLD
12   13  52.346208        -1      HOLD
13   14  53.142763        -1      HOLD
14   15  53.228172        -1      HOLD
15   16  52.873545        -1      HOLD
16   17  52.807033        -1      HOLD
17   18  52.798354        -1      HOLD
18   19  52.747808        -1      HOLD
19   20  52.465788        -1      HOLD
20   21  52.376270        -1      HOLD
21   22  52.881800        -1      HOLD
22   23  53.342298        -1      HOLD
23   24  54.308843        -1      HOLD
24   25  53.911161        -1      HOLD
25   26  53.405393        -1      HOLD
26   27  54.480783        -1      HOLD
27   28  54.693353        -1      HOLD
28   29  54.913929        -1      HOLD
29   30  54.505209        -1      HOLD
30   31  54.724156        -1      HOLD
31   32  54.774017        -1      HOLD
32   33  54.806720        -1      HOLD
33   34  55.418936        -1      HOLD
34   35  55.034136        -1      HOLD
35   36  55.130196        -1      HOLD
36   37  54.268569        -1      HOLD
37   38  54.499199        -1      HOLD
38   39  53.956516        -1      HOLD
39   40  54.868205        -1      HOLD
40   41  54.201773        -1      HOLD
41   42  55.020469        -1      HOLD
42   43  54.608999        -1      HOLD
43   44  53.809945        -1      HOLD
44   45  53.923201        -1      HOLD
45   46  54.040150        -1      HOLD
46   47  53.566538        -1      HOLD
47   48  52.935750        -1      HOLD
48   49  51.740817        -1      HOLD
49   50  51.574180        -1      HOLD
50   51  51.745939        -1      HOLD
51   52  50.732008        -1      HOLD
52   53  50.797717        -1      HOLD
53   54  51.599334        -1      HOLD
54   55  50.717177        -1      HOLD
55   56  51.000429        -1      HOLD
56   57  51.274823        -1      HOLD
57   58  50.967255        -1      HOLD
58   59  51.129028        -1      HOLD
59   60  50.577431        -1      HOLD</code></pre>
</div>
</div>
<div id="cell-19" class="cell" data-outputid="b37c2c04-476f-4fea-c678-759c4158ec6e" data-execution_count="12">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot with Buy/Sell Markers</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>plt.plot(df[<span class="st">'Day'</span>], df[<span class="st">'Price'</span>], color<span class="op">=</span><span class="st">'gray'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="st">'Price'</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify markers for the plot</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>buys <span class="op">=</span> df[df[<span class="st">'Action'</span>] <span class="op">==</span> <span class="st">"GO LONG"</span>]</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>sells <span class="op">=</span> df[df[<span class="st">'Action'</span>] <span class="op">==</span> <span class="st">"GO SHORT"</span>]</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>plt.scatter(buys[<span class="st">'Day'</span>], buys[<span class="st">'Price'</span>], color<span class="op">=</span><span class="st">'green'</span>, marker<span class="op">=</span><span class="st">'^'</span>, label<span class="op">=</span><span class="st">'GO LONG'</span>, s<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>plt.scatter(sells[<span class="st">'Day'</span>], sells[<span class="st">'Price'</span>], color<span class="op">=</span><span class="st">'red'</span>, marker<span class="op">=</span><span class="st">'v'</span>, label<span class="op">=</span><span class="st">'GO SHORT'</span>, s<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">52</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>, label<span class="op">=</span><span class="st">'Short Threshold'</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">48</span>, color<span class="op">=</span><span class="st">'green'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>, label<span class="op">=</span><span class="st">'Long Threshold'</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Part 2: Trading Rules Visualization'</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AD561_Assignment1_BdeGouw_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-20" class="cell" data-outputid="0b1d7e04-170d-4e90-8118-17cd9be63390" data-execution_count="13">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>num_trades <span class="op">=</span> df[df[<span class="st">'Action'</span>] <span class="op">!=</span> <span class="st">'HOLD'</span>].shape[<span class="dv">0</span>]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>num_longs <span class="op">=</span> df[df[<span class="st">'Action'</span>] <span class="op">==</span> <span class="st">'GO LONG'</span>].shape[<span class="dv">0</span>]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>num_shorts <span class="op">=</span> df[df[<span class="st">'Action'</span>] <span class="op">==</span> <span class="st">'GO SHORT'</span>].shape[<span class="dv">0</span>]</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"You made a total of </span><span class="sc">{</span>num_trades<span class="sc">}</span><span class="ss"> trades (excluding 'HOLD' actions)."</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  - </span><span class="sc">{</span>num_longs<span class="sc">}</span><span class="ss"> 'GO LONG' trades"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  - </span><span class="sc">{</span>num_shorts<span class="sc">}</span><span class="ss"> 'GO SHORT' trades"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>You made a total of 1 trades (excluding 'HOLD' actions).
  - 0 'GO LONG' trades
  - 1 'GO SHORT' trades</code></pre>
</div>
</div>
<p>I made my first trade on day 8, where I shorted at the price of $52.12.</p>
<p>I made 1 ‘GO SHORT’ trade, which accounted for all of the total trades that I made. There were no ‘GO LONG’ trades made.</p>
<p>Honestly, no. This rule did not feel reasonable for this series as there was only one short position and no long positions taken at all. There were no points where the price dropped below $48, so the long position was never triggered. Additonally, there was a prolonged period of time after the short where the position occured losses, without a clear exit stretegy. The strategy was stuck in lopsided exposure to the short. The overall performance was due to a significant recovery, but this is not a reproducable account of what may happen if this rule was to be repeated. This strategy succeeded only due to the trend reversal before the loses became too big.</p>
<p>Since that there were only short values taken above the $52 dollar price range, the short position looked poorly timed as it occured at a period of time where there was a sustained upwards trend. As the price continued to rise, the position experienced a significant losses (entered at $52.12m peaked at $55.42, representing a $3.30 adverse move) before eventually reversing. While there was only one short trade, it was exposed to long-term trend risk as the price continued to rise for several weeks after the short was made, meaning there was unrealized loss before eventuall reversing.</p>
</section>
<section id="part-3-turn-actions-into-money" class="level1">
<h1>Part 3: Turn Actions Into Money</h1>
<div id="cell-23" class="cell" data-outputid="6e050a99-3667-462e-e83d-febd77e3ed0a" data-execution_count="25">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Daily P&amp;L</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Exposure is $1,000 per unit (Position 1 = $1000, Position -1 = -$1000)</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>exposure <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Daily Price Change: Price(today) - Price(yesterday)</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Price_Change'</span>] <span class="op">=</span> df[<span class="st">'Price'</span>].diff()</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Daily P&amp;L = Position(yesterday) * Price_Change(today) * (Exposure / StartPrice)</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Daily_PnL'</span>] <span class="op">=</span> df[<span class="st">'Position'</span>].shift(<span class="dv">1</span>) <span class="op">*</span> df[<span class="st">'Price_Change'</span>] <span class="op">*</span> (exposure <span class="op">/</span> <span class="dv">50</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Daily_PnL'</span>] <span class="op">=</span> df[<span class="st">'Daily_PnL'</span>].fillna(<span class="dv">0</span>) <span class="co"># First day has no P&amp;L</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Cumulative P&amp;L</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Cumulative_PnL'</span>] <span class="op">=</span> df[<span class="st">'Daily_PnL'</span>].cumsum()</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Table displaying results for all 60 days</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">--- PART 3: Full Financial Results ---"</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">'display.max_rows'</span>, <span class="va">None</span>) <span class="co"># Ensure all 60 days print</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[[<span class="st">'Day'</span>, <span class="st">'Price'</span>, <span class="st">'Position'</span>, <span class="st">'Action'</span>, <span class="st">'Daily_PnL'</span>, <span class="st">'Cumulative_PnL'</span>]].to_string(index<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--- PART 3: Full Financial Results ---
 Day     Price  Position   Action  Daily_PnL  Cumulative_PnL
   1 50.000000         0     HOLD    0.00000         0.00000
   2 49.593192         0     HOLD   -0.00000         0.00000
   3 49.945004         0     HOLD    0.00000         0.00000
   4 49.810933         0     HOLD   -0.00000         0.00000
   5 49.569653         0     HOLD   -0.00000         0.00000
   6 50.191958         0     HOLD    0.00000         0.00000
   7 50.530388         0     HOLD    0.00000         0.00000
   8 52.124140        -1 GO SHORT    0.00000         0.00000
   9 51.583857        -1     HOLD   10.80566        10.80566
  10 51.588972        -1     HOLD   -0.10230        10.70336
  11 51.807887        -1     HOLD   -4.37830         6.32506
  12 52.471780        -1     HOLD  -13.27786        -6.95280
  13 52.346208        -1     HOLD    2.51144        -4.44136
  14 53.142763        -1     HOLD  -15.93110       -20.37246
  15 53.228172        -1     HOLD   -1.70818       -22.08064
  16 52.873545        -1     HOLD    7.09254       -14.98810
  17 52.807033        -1     HOLD    1.33024       -13.65786
  18 52.798354        -1     HOLD    0.17358       -13.48428
  19 52.747808        -1     HOLD    1.01092       -12.47336
  20 52.465788        -1     HOLD    5.64040        -6.83296
  21 52.376270        -1     HOLD    1.79036        -5.04260
  22 52.881800        -1     HOLD  -10.11060       -15.15320
  23 53.342298        -1     HOLD   -9.20996       -24.36316
  24 54.308843        -1     HOLD  -19.33090       -43.69406
  25 53.911161        -1     HOLD    7.95364       -35.74042
  26 53.405393        -1     HOLD   10.11536       -25.62506
  27 54.480783        -1     HOLD  -21.50780       -47.13286
  28 54.693353        -1     HOLD   -4.25140       -51.38426
  29 54.913929        -1     HOLD   -4.41152       -55.79578
  30 54.505209        -1     HOLD    8.17440       -47.62138
  31 54.724156        -1     HOLD   -4.37894       -52.00032
  32 54.774017        -1     HOLD   -0.99722       -52.99754
  33 54.806720        -1     HOLD   -0.65406       -53.65160
  34 55.418936        -1     HOLD  -12.24432       -65.89592
  35 55.034136        -1     HOLD    7.69600       -58.19992
  36 55.130196        -1     HOLD   -1.92120       -60.12112
  37 54.268569        -1     HOLD   17.23254       -42.88858
  38 54.499199        -1     HOLD   -4.61260       -47.50118
  39 53.956516        -1     HOLD   10.85366       -36.64752
  40 54.868205        -1     HOLD  -18.23378       -54.88130
  41 54.201773        -1     HOLD   13.32864       -41.55266
  42 55.020469        -1     HOLD  -16.37392       -57.92658
  43 54.608999        -1     HOLD    8.22940       -49.69718
  44 53.809945        -1     HOLD   15.98108       -33.71610
  45 53.923201        -1     HOLD   -2.26512       -35.98122
  46 54.040150        -1     HOLD   -2.33898       -38.32020
  47 53.566538        -1     HOLD    9.47224       -28.84796
  48 52.935750        -1     HOLD   12.61576       -16.23220
  49 51.740817        -1     HOLD   23.89866         7.66646
  50 51.574180        -1     HOLD    3.33274        10.99920
  51 51.745939        -1     HOLD   -3.43518         7.56402
  52 50.732008        -1     HOLD   20.27862        27.84264
  53 50.797717        -1     HOLD   -1.31418        26.52846
  54 51.599334        -1     HOLD  -16.03234        10.49612
  55 50.717177        -1     HOLD   17.64314        28.13926
  56 51.000429        -1     HOLD   -5.66504        22.47422
  57 51.274823        -1     HOLD   -5.48788        16.98634
  58 50.967255        -1     HOLD    6.15136        23.13770
  59 51.129028        -1     HOLD   -3.23546        19.90224
  60 50.577431        -1     HOLD   11.03194        30.93418</code></pre>
</div>
</div>
<div id="cell-24" class="cell" data-outputid="e241303d-970b-49af-c74a-e2c52f21e2b9" data-execution_count="26">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot of Cumulative P&amp;L</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>plt.plot(df[<span class="st">'Day'</span>], df[<span class="st">'Cumulative_PnL'</span>], color<span class="op">=</span><span class="st">'darkgreen'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'-'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Cumulative Profit and Loss Over 60 Days'</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Day'</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cumulative P&amp;L ($)'</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>plt.fill_between(df[<span class="st">'Day'</span>], df[<span class="st">'Cumulative_PnL'</span>], <span class="dv">0</span>, where<span class="op">=</span>(df[<span class="st">'Cumulative_PnL'</span>] <span class="op">&gt;=</span> <span class="dv">0</span>), color<span class="op">=</span><span class="st">'green'</span>, alpha<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>plt.fill_between(df[<span class="st">'Day'</span>], df[<span class="st">'Cumulative_PnL'</span>], <span class="dv">0</span>, where<span class="op">=</span>(df[<span class="st">'Cumulative_PnL'</span>] <span class="op">&lt;</span> <span class="dv">0</span>), color<span class="op">=</span><span class="st">'red'</span>, alpha<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AD561_Assignment1_BdeGouw_files/figure-html/cell-16-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>By day 30, I was down $-47.62 dollars.</p>
<p>My final cummulative profit was $30.93, which shows that I made a substantial recovery of close to $80 dollars by the time I reached day 60. This recovery is important because it shows that I was able to recovery to from a deficit 2x as larged as the final profits, suggesting that the final outcome for this time window is purely down to timing of when the window ends. If the window had ended on day 34, there would be a very different outcome. This shows that this trading is highly path dependent and depends when the sample ends</p>
<p>Yes, I experienced a very significant losing streak for 36 days straight. It started at day 12, where my cummulative profits went below $0 for the first time at a value of $-6.95, reaching its biggest cummualtive loss in day 34, where the price was $-65.89. The last day in a loss was day 48, where the price was at a loss of $-16.23. On day 49, the price then became positive again and remained so for the rest of this price window.</p>
<p>Overall, the strategy saw a maximum drawdown of $-65.89, and ended up ultimately earning $30.93, meaning the maximum loss was more than twice the final profits. While the overall startegy worked, the combination of time in loss and signficant bounceback to be profitable by the end of the window shows their is limited risk control and future outcomes are fragile.</p>
</section>
<section id="part-4-add-leverage" class="level1">
<h1>Part 4: Add Leverage</h1>
<div id="cell-27" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate 10x Exposure</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>leverage_factor <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>exposure_1x <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>exposure_10x <span class="op">=</span> exposure_1x <span class="op">*</span> leverage_factor</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Daily and Cumulative P&amp;L for both versions</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Using (exposure / 50) as the multiplier for price movement points</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>multiplier_1x <span class="op">=</span> exposure_1x <span class="op">/</span> <span class="dv">50</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>multiplier_10x <span class="op">=</span> exposure_10x <span class="op">/</span> <span class="dv">50</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="co"># P&amp;L 1x</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Daily_PnL_1x'</span>] <span class="op">=</span> df[<span class="st">'Position'</span>].shift(<span class="dv">1</span>) <span class="op">*</span> df[<span class="st">'Price_Change'</span>] <span class="op">*</span> multiplier_1x</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Daily_PnL_1x'</span>] <span class="op">=</span> df[<span class="st">'Daily_PnL_1x'</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Cumulative_PnL_1x'</span>] <span class="op">=</span> df[<span class="st">'Daily_PnL_1x'</span>].cumsum()</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="co"># P&amp;L 10x</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Daily_PnL_10x'</span>] <span class="op">=</span> df[<span class="st">'Position'</span>].shift(<span class="dv">1</span>) <span class="op">*</span> df[<span class="st">'Price_Change'</span>] <span class="op">*</span> multiplier_10x</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Daily_PnL_10x'</span>] <span class="op">=</span> df[<span class="st">'Daily_PnL_10x'</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Cumulative_PnL_10x'</span>] <span class="op">=</span> df[<span class="st">'Daily_PnL_10x'</span>].cumsum()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-28" class="cell" data-outputid="103d5992-4c08-4ed4-bb08-080582eb09b9" data-execution_count="17">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Table displaying results for all 60 days including both 1x and 10x</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">--- PART 4: Full Leveraged Results (1x vs 10x) ---"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>cols_to_show <span class="op">=</span> [<span class="st">'Day'</span>, <span class="st">'Price'</span>, <span class="st">'Position'</span>, <span class="st">'Daily_PnL_1x'</span>, <span class="st">'Cumulative_PnL_1x'</span>, <span class="st">'Daily_PnL_10x'</span>, <span class="st">'Cumulative_PnL_10x'</span>]</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[cols_to_show].to_string(index<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--- PART 4: Full Leveraged Results (1x vs 10x) ---
 Day     Price  Position  Daily_PnL_1x  Cumulative_PnL_1x  Daily_PnL_10x  Cumulative_PnL_10x
   1 50.000000         0       0.00000            0.00000         0.0000              0.0000
   2 49.593192         0      -0.00000            0.00000        -0.0000              0.0000
   3 49.945004         0       0.00000            0.00000         0.0000              0.0000
   4 49.810933         0      -0.00000            0.00000        -0.0000              0.0000
   5 49.569653         0      -0.00000            0.00000        -0.0000              0.0000
   6 50.191958         0       0.00000            0.00000         0.0000              0.0000
   7 50.530388         0       0.00000            0.00000         0.0000              0.0000
   8 52.124140        -1       0.00000            0.00000         0.0000              0.0000
   9 51.583857        -1      10.80566           10.80566       108.0566            108.0566
  10 51.588972        -1      -0.10230           10.70336        -1.0230            107.0336
  11 51.807887        -1      -4.37830            6.32506       -43.7830             63.2506
  12 52.471780        -1     -13.27786           -6.95280      -132.7786            -69.5280
  13 52.346208        -1       2.51144           -4.44136        25.1144            -44.4136
  14 53.142763        -1     -15.93110          -20.37246      -159.3110           -203.7246
  15 53.228172        -1      -1.70818          -22.08064       -17.0818           -220.8064
  16 52.873545        -1       7.09254          -14.98810        70.9254           -149.8810
  17 52.807033        -1       1.33024          -13.65786        13.3024           -136.5786
  18 52.798354        -1       0.17358          -13.48428         1.7358           -134.8428
  19 52.747808        -1       1.01092          -12.47336        10.1092           -124.7336
  20 52.465788        -1       5.64040           -6.83296        56.4040            -68.3296
  21 52.376270        -1       1.79036           -5.04260        17.9036            -50.4260
  22 52.881800        -1     -10.11060          -15.15320      -101.1060           -151.5320
  23 53.342298        -1      -9.20996          -24.36316       -92.0996           -243.6316
  24 54.308843        -1     -19.33090          -43.69406      -193.3090           -436.9406
  25 53.911161        -1       7.95364          -35.74042        79.5364           -357.4042
  26 53.405393        -1      10.11536          -25.62506       101.1536           -256.2506
  27 54.480783        -1     -21.50780          -47.13286      -215.0780           -471.3286
  28 54.693353        -1      -4.25140          -51.38426       -42.5140           -513.8426
  29 54.913929        -1      -4.41152          -55.79578       -44.1152           -557.9578
  30 54.505209        -1       8.17440          -47.62138        81.7440           -476.2138
  31 54.724156        -1      -4.37894          -52.00032       -43.7894           -520.0032
  32 54.774017        -1      -0.99722          -52.99754        -9.9722           -529.9754
  33 54.806720        -1      -0.65406          -53.65160        -6.5406           -536.5160
  34 55.418936        -1     -12.24432          -65.89592      -122.4432           -658.9592
  35 55.034136        -1       7.69600          -58.19992        76.9600           -581.9992
  36 55.130196        -1      -1.92120          -60.12112       -19.2120           -601.2112
  37 54.268569        -1      17.23254          -42.88858       172.3254           -428.8858
  38 54.499199        -1      -4.61260          -47.50118       -46.1260           -475.0118
  39 53.956516        -1      10.85366          -36.64752       108.5366           -366.4752
  40 54.868205        -1     -18.23378          -54.88130      -182.3378           -548.8130
  41 54.201773        -1      13.32864          -41.55266       133.2864           -415.5266
  42 55.020469        -1     -16.37392          -57.92658      -163.7392           -579.2658
  43 54.608999        -1       8.22940          -49.69718        82.2940           -496.9718
  44 53.809945        -1      15.98108          -33.71610       159.8108           -337.1610
  45 53.923201        -1      -2.26512          -35.98122       -22.6512           -359.8122
  46 54.040150        -1      -2.33898          -38.32020       -23.3898           -383.2020
  47 53.566538        -1       9.47224          -28.84796        94.7224           -288.4796
  48 52.935750        -1      12.61576          -16.23220       126.1576           -162.3220
  49 51.740817        -1      23.89866            7.66646       238.9866             76.6646
  50 51.574180        -1       3.33274           10.99920        33.3274            109.9920
  51 51.745939        -1      -3.43518            7.56402       -34.3518             75.6402
  52 50.732008        -1      20.27862           27.84264       202.7862            278.4264
  53 50.797717        -1      -1.31418           26.52846       -13.1418            265.2846
  54 51.599334        -1     -16.03234           10.49612      -160.3234            104.9612
  55 50.717177        -1      17.64314           28.13926       176.4314            281.3926
  56 51.000429        -1      -5.66504           22.47422       -56.6504            224.7422
  57 51.274823        -1      -5.48788           16.98634       -54.8788            169.8634
  58 50.967255        -1       6.15136           23.13770        61.5136            231.3770
  59 51.129028        -1      -3.23546           19.90224       -32.3546            199.0224
  60 50.577431        -1      11.03194           30.93418       110.3194            309.3418</code></pre>
</div>
</div>
<div id="cell-29" class="cell" data-outputid="8bfc9cc0-c52b-47bc-feb1-7aacba691432" data-execution_count="28">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot Equity Curves together</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting both curves</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>plt.plot(df[<span class="st">'Day'</span>], df[<span class="st">'Cumulative_PnL_1x'</span>], label<span class="op">=</span><span class="st">'1x Strategy (Standard)'</span>, color<span class="op">=</span><span class="st">'blue'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>plt.plot(df[<span class="st">'Day'</span>], df[<span class="st">'Cumulative_PnL_10x'</span>], label<span class="op">=</span><span class="st">'10x Strategy (Leveraged)'</span>, color<span class="op">=</span><span class="st">'orange'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Formatting the chart</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Equity Curve Comparison: 1x vs 10x Leverage'</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Day'</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Total Profit/Loss ($)'</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding shading to highlight the magnitude difference</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>plt.fill_between(df[<span class="st">'Day'</span>], df[<span class="st">'Cumulative_PnL_10x'</span>], df[<span class="st">'Cumulative_PnL_1x'</span>], color<span class="op">=</span><span class="st">'orange'</span>, alpha<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AD561_Assignment1_BdeGouw_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Yes, the leverage did change my final profits. At 10x leverage, my final cummulative profit is $309.34, which is substaintially bigger than the cummulative profit when I was unleveraged. This is inly a mechanical difference, as the leverage magnified my volatility, but does not fundamentally change the strategy of the trades made.</p>
<p>Yes, for sure. As we became more leveraged (10x), the changes in the price meant that the size of profit and losses were larger. At the points in which the losses were at their largest, we had a cummulative loss of greater than $-658.959237 dollars. However, it is important to note that while the ‘scariness’ of the potential increased losses is matched in the opposite effect where the gain in profits is also substaintially larger than before. Leveraging at 10x multiple can both exaggerate the losses and profits that can be gained. The leverage not only provides a potential increase in upside, but increases the probability of ruin if there is any need to stop trading or cut losses or future capital constraints.</p>
<p>The highest equity value reached (when there is a fall afterwards), was $108.05 on day 9. It is important to note that this is not not the highest equity value reached - which is actually $309.34, but this was the final day so there was no fall after this point from the data that we have collected for this 60 day window.</p>
<p>At its worst, the equity fell to a cummulative loss of $-658.959237. From day 9, the last profit before the loss, this is a $766 swing downward, which shows the extreme volatility experienced due to the volatility. It is important to note this as it represents an unfavorable risk-to-reward asymmetry, despite ending up with an overall total profit.</p>
<p>This worst cummulative loss occured on day 34.</p>
</section>
<section id="part-5-introduce-a-survival-rule" class="level1">
<h1>Part 5: Introduce a Survival Rule</h1>
<div id="cell-32" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>stop_limit <span class="op">=</span> <span class="op">-</span><span class="dv">2000</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>stopped_out <span class="op">=</span> <span class="va">False</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>stop_day <span class="op">=</span> <span class="va">None</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># We create new columns for the "Stopped" version of the strategy</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Position_Stopped'</span>] <span class="op">=</span> df[<span class="st">'Position'</span>]</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Daily_PnL_Stopped'</span>] <span class="op">=</span> df[<span class="st">'Daily_PnL_10x'</span>]</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(df)):</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check if we were already stopped out in a previous day</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> stopped_out:</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>        df.at[i, <span class="st">'Position_Stopped'</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>        df.at[i, <span class="st">'Action'</span>] <span class="op">=</span> <span class="st">"STOPPED"</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>        df.at[i, <span class="st">'Daily_PnL_Stopped'</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Check if today's cumulative loss hits the limit</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>        <span class="co"># We calculate temporary cumulative PnL to check the condition</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>        current_cum_pnl <span class="op">=</span> df[<span class="st">'Daily_PnL_Stopped'</span>].iloc[:i<span class="op">+</span><span class="dv">1</span>].<span class="bu">sum</span>()</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> current_cum_pnl <span class="op">&lt;=</span> stop_limit:</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>            stopped_out <span class="op">=</span> <span class="va">True</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>            stop_day <span class="op">=</span> df.at[i, <span class="st">'Day'</span>]</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>            <span class="co"># We allow the loss that triggered the stop, but set position to 0 for the future</span></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>            df.at[i, <span class="st">'Position'</span>] <span class="op">=</span> <span class="dv">0</span> <span class="co"># Ensure original 'Position' is not kept if stopped out</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>            df.at[i, <span class="st">'Action'</span>] <span class="op">=</span> <span class="st">"LIQUIDATED"</span></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>            df.at[i, <span class="st">'Position_Stopped'</span>] <span class="op">=</span> <span class="dv">0</span> <span class="co"># Set Position_Stopped to 0 after liquidation</span></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Recalculate Daily_PnL_Stopped based on the updated Position_Stopped for the stopping logic</span></span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Daily_PnL_Stopped'</span>] <span class="op">=</span> df[<span class="st">'Position_Stopped'</span>].shift(<span class="dv">1</span>) <span class="op">*</span> df[<span class="st">'Price_Change'</span>] <span class="op">*</span> multiplier_10x</span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Daily_PnL_Stopped'</span>] <span class="op">=</span> df[<span class="st">'Daily_PnL_Stopped'</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Cumulative_PnL_Stopped'</span>] <span class="op">=</span> df[<span class="st">'Daily_PnL_Stopped'</span>].cumsum()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-33" class="cell" data-outputid="a2c0509a-94a2-4728-8fa3-2900aead4ef8" data-execution_count="30">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot comparing the original 10x vs the Stopped 10x</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>plt.plot(df[<span class="st">'Day'</span>], df[<span class="st">'Cumulative_PnL_10x'</span>], label<span class="op">=</span><span class="st">'Original 10x (No Stop)'</span>, color<span class="op">=</span><span class="st">'orange'</span>, alpha<span class="op">=</span><span class="fl">0.4</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>plt.plot(df[<span class="st">'Day'</span>], df[<span class="st">'Cumulative_PnL_Stopped'</span>], label<span class="op">=</span><span class="st">'Stopped 10x (Risk Managed)'</span>, color<span class="op">=</span><span class="st">'red'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> stop_day:</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    plt.axvline(x<span class="op">=</span>stop_day, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="ss">f'Stop Triggered (Day </span><span class="sc">{</span>stop_day<span class="sc">}</span><span class="ss">)'</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    plt.annotate(<span class="st">'STOP OUT'</span>, xy<span class="op">=</span>(stop_day, stop_limit), xytext<span class="op">=</span>(stop_day<span class="op">+</span><span class="dv">2</span>, stop_limit<span class="op">-</span><span class="dv">500</span>),</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>                 arrowprops<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">'black'</span>, shrink<span class="op">=</span><span class="fl">0.05</span>))</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>plt.axhline(stop_limit, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, label<span class="op">=</span><span class="st">'Stop Limit (-$2,000)'</span>)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Impact of Mandatory Stop-Out Rule at -$2,000'</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Day'</span>)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cumulative P&amp;L ($)'</span>)</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the table around the stop-out day</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> stop_day:</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"--- Strategy stopped on Day </span><span class="sc">{</span>stop_day<span class="sc">}</span><span class="ss"> ---"</span>)</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(df[[<span class="st">'Day'</span>, <span class="st">'Price'</span>, <span class="st">'Action'</span>, <span class="st">'Cumulative_PnL_10x'</span>, <span class="st">'Cumulative_PnL_Stopped'</span>]].iloc[<span class="bu">max</span>(<span class="dv">0</span>, stop_day<span class="op">-</span><span class="dv">5</span>):stop_day<span class="op">+</span><span class="dv">5</span>])</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"The strategy never dropped below -$2,000. No stop-out occurred."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AD561_Assignment1_BdeGouw_files/figure-html/cell-21-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>The strategy never dropped below -$2,000. No stop-out occurred.</code></pre>
</div>
</div>
<p>No I did not hit the stop-loss rule.</p>
<p>I did not stop, so there was no continuation.</p>
<p>However, if the limit stopped me earlier at a different threshold - for example. at $-500, would have stopped me around day 28. The strategy would have led to me exiting with a significant loss and any potential recovery would not have eventuated. Therefore, because the strategy tolerated a bigger drawdown, I was able to continue and realise the eventual profits. The strategy did not succeed because it was immediately correct, but because it survived being wrong long enough for the price to reverse.</p>
<p>The strategy is fragile because its success depends heavily on the chosen stop threshold and the ability to tolerate large drawdowns. A tighter stop (such as $-500) would have reduced the maximum drawdown, but it also would have locked in a permanent loss and eliminated the eventual recovery.Since the $-2000 stop was far below the actual drawdown experienced, it never constrained the strategy, meaning the survival rule did not meaningfully limit risk in this simulation. The strategys overall success is dependent on tolerating large drawdowns, yet is very fragile as changes in the risk constraints may dramatically change the outcomes as it may trigger the chosen stop threshold.</p>
</section>
<section id="part-6-a-tiny-shock" class="level1">
<h1>Part 6: A Tiny Shock</h1>
<div id="cell-36" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose a 3-day window</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>shock_days <span class="op">=</span> [<span class="dv">15</span>, <span class="dv">16</span>, <span class="dv">17</span>]</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>df_shock <span class="op">=</span> df.copy()</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the +4 price shock</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>df_shock.loc[df_shock[<span class="st">'Day'</span>].isin(shock_days), <span class="st">'Price'</span>] <span class="op">+=</span> <span class="dv">4</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Recalculate everything for the 10x Stop-Loss Strategy</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>df_shock[<span class="st">'Price_Change'</span>] <span class="op">=</span> df_shock[<span class="st">'Price'</span>].diff()</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Use Position from df (which includes any original stop-out) to calculate PnL</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>df_shock[<span class="st">'Daily_PnL_10x_Shocked'</span>] <span class="op">=</span> df_shock[<span class="st">'Position'</span>].shift(<span class="dv">1</span>) <span class="op">*</span> df_shock[<span class="st">'Price_Change'</span>] <span class="op">*</span> (<span class="dv">1000</span> <span class="op">/</span> <span class="dv">50</span> <span class="op">*</span> <span class="dv">10</span>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>df_shock[<span class="st">'Daily_PnL_10x_Shocked'</span>] <span class="op">=</span> df_shock[<span class="st">'Daily_PnL_10x_Shocked'</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply Stop-Loss Logic ($ -2,000 threshold) specifically for the shocked scenario</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>stopped_out_shock <span class="op">=</span> <span class="va">False</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>stop_day_shock <span class="op">=</span> <span class="va">None</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>daily_pnl_stopped_shocked <span class="op">=</span> []</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>current_cum_pnl_shocked <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(df_shock)):</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> stopped_out_shock:</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>        daily_pnl_stopped_shocked.append(<span class="dv">0</span>)</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>        pnl_today <span class="op">=</span> df_shock[<span class="st">'Daily_PnL_10x_Shocked'</span>].iloc[i]</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>        current_cum_pnl_shocked <span class="op">+=</span> pnl_today</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> current_cum_pnl_shocked <span class="op">&lt;=</span> <span class="op">-</span><span class="dv">2000</span>:</span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>            stopped_out_shock <span class="op">=</span> <span class="va">True</span></span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>            stop_day_shock <span class="op">=</span> df_shock.at[i, <span class="st">'Day'</span>]</span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>            daily_pnl_stopped_shocked.append(pnl_today) <span class="co"># Include the final blow</span></span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a>            daily_pnl_stopped_shocked.append(pnl_today)</span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a>df_shock[<span class="st">'Cumulative_PnL_Stopped'</span>] <span class="op">=</span> np.cumsum(daily_pnl_stopped_shocked)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-37" class="cell" data-outputid="610b6df9-10e7-4c4c-d3a5-75dadb90761e" data-execution_count="32">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>plt.plot(df_shock[<span class="st">'Day'</span>], df_shock[<span class="st">'Cumulative_PnL_Stopped'</span>], color<span class="op">=</span><span class="st">'purple'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'Shocked Strategy (10x)'</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="op">-</span><span class="dv">2000</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, label<span class="op">=</span><span class="st">'Stop Limit (-$2,000)'</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> stop_day_shock:</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    plt.scatter(stop_day_shock, df_shock.loc[df_shock[<span class="st">'Day'</span>]<span class="op">==</span>stop_day_shock, <span class="st">'Cumulative_PnL_Stopped'</span>],</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">'black'</span>, zorder<span class="op">=</span><span class="dv">5</span>, label<span class="op">=</span><span class="ss">f'Liquidated Day </span><span class="sc">{</span>stop_day_shock<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="ss">f'10x Strategy with +$4 Price Shock on Days </span><span class="sc">{</span>shock_days<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Day'</span>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cumulative P&amp;L ($)'</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AD561_Assignment1_BdeGouw_files/figure-html/cell-23-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-38" class="cell" data-outputid="d906d944-fd88-486d-f69c-b99ae4d5b665" data-execution_count="33">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"--- Shocked Strategy Performance around Days </span><span class="sc">{</span>shock_days<span class="sc">}</span><span class="ss"> ---"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_shock[[<span class="st">'Day'</span>, <span class="st">'Price'</span>, <span class="st">'Position'</span>, <span class="st">'Daily_PnL_10x_Shocked'</span>, <span class="st">'Cumulative_PnL_Stopped'</span>]].iloc[shock_days[<span class="dv">0</span>]<span class="op">-</span><span class="dv">2</span> : shock_days[<span class="op">-</span><span class="dv">1</span>]<span class="op">+</span><span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>--- Shocked Strategy Performance around Days [15, 16, 17] ---
    Day      Price  Position  Daily_PnL_10x_Shocked  Cumulative_PnL_Stopped
13   14  53.142763        -1              -159.3110               -203.7246
14   15  57.228172        -1              -817.0818              -1020.8064
15   16  56.873545        -1                70.9254               -949.8810
16   17  56.807033        -1                13.3024               -936.5786
17   18  52.798354        -1               801.7358               -134.8428
18   19  52.747808        -1                10.1092               -124.7336</code></pre>
</div>
</div>
<div id="cell-39" class="cell" data-outputid="3feb605e-ea3d-48b2-8856-621ce0ac74aa" data-execution_count="34">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Final Cumulative P&amp;L (Original 1x Leverage): $</span><span class="sc">{</span>df[<span class="st">'Cumulative_PnL'</span>]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Final Cumulative P&amp;L (10x Leveraged Strategy): $</span><span class="sc">{</span>df[<span class="st">'Cumulative_PnL_10x'</span>]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Final Cumulative P&amp;L (Stopped 10x Leveraged Strategy): $</span><span class="sc">{</span>df[<span class="st">'Cumulative_PnL_Stopped'</span>]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Final Cumulative P&amp;L (Shocked 10x Leveraged Strategy): $</span><span class="sc">{</span>df_shock[<span class="st">'Cumulative_PnL_Stopped'</span>]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Final Cumulative P&amp;L (Original 1x Leverage): $30.93
Final Cumulative P&amp;L (10x Leveraged Strategy): $309.34
Final Cumulative P&amp;L (Stopped 10x Leveraged Strategy): $309.34
Final Cumulative P&amp;L (Shocked 10x Leveraged Strategy): $309.34</code></pre>
</div>
</div>
<p>No the shock did not change the final profits. The final profits remained at $309.34. This is likely bececause the shock occured early on the the trading window which allowed the profits to recover over the remainder of the window. Fundamentally, the price shock changes the risk exposure, even while the ending profit was the same.</p>
<p>No it did not change whether I survived as it did not get close to the $2000 stop limit. The lowest value it got to was $-1020.8064 on day 15, meaning there was a buffer of $979~. However, this is a significant changes as it represents roughly a 55% increase in the maximum drawdown from just a 3-day $4 price shock. The closest the buffer was to the lowest value prior to the shock was $1342, meaning the shock reduced the buffer by roughly $360. Although the final profits didnt change, the risk profile drastically shifted.</p>
<p>Overall, the rule mattered more as the price shock did not impact the overall profits. This meant that althought the shock may have affected profits in the short-term, it played no significant impact on the overall returns for this time period. While we never encountered a situation where the price stop limit was reached, the rule is still ultimately more important as it would have determined overall survival, by stopping a significant loss in the realm where the cummulative profits would not have been able to recover. However it is important to note, that the shock is still important - it chnaged how close I came to hitting the stop marker meaning it could have potentially been more important. The rule in this instance regulates the boundary of loss, while the short-run luck experienced by the shocl determines how close we land to that boundary. Based on this specific simulation, the stop rule ultimately determined survival because the shock did not push the strategy beyond the loss boundary. However, the shock significantly reduced the margin of safety, demonstrating that short-run path changes can affect how fragile survival becomes.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/bdegouw\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>