project:
  type: website
  resources:
    - documents/**
    - photos/**

website:
  title: "<img src='photos/bdglogo.png' style='height:22px; margin-right:8px;'> Bowen de Gouw"
  favicon: "photos/bdglogo.png"
  site-url: "https://bdegouw.github.io/"
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - href: professionalsummary.qmd
        text: Professional Summary
      - text: Academics
        menu:
          - text: Academic Coursework
            href: classes.qmd
          - text: Marketing Analytics
            href: marketing_analytics.qmd
          - text: Financial Analytics
            href: financial_analytics.qmd
          - text: Cloud Analytics
            href: cloud_analytics.qmd
      - href: blog.qmd
        text: Blog
      - href: gallery.qmd
        text: Photo Gallery
      - href: side_projects.qmd
        text: Side Projects
      - href: contact.qmd
        text: Contact Me
  search: false
  page-navigation: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true