name: Build site
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install jupyter ipykernel
          python -m ipykernel install --user --name "ci-py312"

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        env:
          QUARTO_PYTHON: ${{ github.workspace }}/.venv/bin/python
        run: |
          quarto check jupyter
          quarto render
